apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-web-app-deployment-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: basic-web-app
      color: blue
  template:
    metadata:
      labels:
        app: basic-web-app
        color: blue
    spec:
      containers:
      - name: web-app 
        image: europe-west4-docker.pkg.dev/public-cloud-concepts-471510/basic-web--app/basic-web-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80 
