name: Build and Push to Artifact Registry

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

env:
  REGION: europe-west4
  PROJECT_ID: public-cloud-concepts-471510 
  REPOSITORY: basic-web--app 
  APP_NAME: basic-web-app 
  CLUSTER_NAME: autopilot-cluster-1   
  CLUSTER_LOCATION: europe-west4      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      - name: Build, Tag and Push Docker images 
        run: | 
          IMAGE_SHA=$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$APP_NAME:${{ github.sha }}
          IMAGE_LATEST=$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$APP_NAME:latest 

          # Build with SHA tag 
          docker build -t $IMAGE_SHA . 

          # Push SHA tag 
          docker push $IMAGE_SHA 

          # Tag as latest and push 
          docker tag $IMAGE_SHA $IMAGE_LATEST 
          docker push $IMAGE_LATEST

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.CLUSTER_LOCATION }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Deploy
        run: |
          kubectl apply -f deployment.yml
          kubectl rollout status deployment/${{ env.APP_NAME }}
          kubectl get pods
